name: Publish Lamar IoC Nugets

on:
  workflow_dispatch:
  push:
    branches:    
      - 'testBranch'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      working-directory: ../
      run: dotnet restore
    - name: Build
      working-directory: ../
      run: dotnet build WebApplication1.sln --configuration Release

    - name: Publish Lamar
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PACKAGE_PATH: "https://nuget.pkg.github.com/anaostashko/index.json"
          PROJECT_FILE_PATH: WebApplication1/WebApplication1.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}